// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsix-T9X7_ESFwDMigHHKiEQa8vyHqLFQ',
    appId: '1:800975618017:android:f9a28ecd05849368551ca0',
    messagingSenderId: '800975618017',
    projectId: 'notes-5fc08',
    storageBucket: 'notes-5fc08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYs428hvA9Oq6AcH4DcUFWKLnW3tkwD7U',
    appId: '1:800975618017:ios:001c664a59069bfa551ca0',
    messagingSenderId: '800975618017',
    projectId: 'notes-5fc08',
    storageBucket: 'notes-5fc08.firebasestorage.app',
    iosBundleId: 'notedevad.blogspot.com.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIgq8x-e6j3zXdfa3oGGposVHP7wHhv8o',
    appId: '1:800975618017:web:645b4e11f5cc8e13551ca0',
    messagingSenderId: '800975618017',
    projectId: 'notes-5fc08',
    authDomain: 'notes-5fc08.firebaseapp.com',
    storageBucket: 'notes-5fc08.firebasestorage.app',
    measurementId: 'G-NH6Y3BDQPN',
  );
}
